[SEASK-71] TPDM Starter Kit - Quick Start - Packer
Ed-Fi-Exchange-OSS/EPP-PowerBI-Report-Starter-Kit pull request #26
Opened 2021-06-29 14:46 UTC by raghuramakrishna

2021-06-29 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Exchange-OSS/EPP-PowerBI-Report-Starter-Kit?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Exchange-OSS/EPP-PowerBI-Report-Starter-Kit?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Exchange-OSS/EPP-PowerBI-Report-Starter-Kit?pullRequest=26) it.</sub>

2021-06-30 16:30 UTC, jamessmckay requested changes
@raghuramakrishna 

The api is not loading the TPDM extension. The extension should show up in the data models if it was loaded correctly.
```
// 20210630112231
// https://win-qv87ia1brr8/WebApi

{
  "version": "5.2",
  "informationalVersion": "5.2",
  "suite": "3",
  "build": "5.2.14406.0",
  "apiMode": "Year Specific",
  "dataModels": [
    {
      "name": "Ed-Fi",
      "version": "3.3.0-a"
    }
  ],
  "urls": {
    "dependencies": "https://win-qv87ia1brr8/WebApi/metadata/data/v3/2021/dependencies",
    "openApiMetadata": "https://win-qv87ia1brr8/WebApi/metadata/2021",
    "oauth": "https://win-qv87ia1brr8/WebApi/oauth/token",
    "dataManagementApi": "https://win-qv87ia1brr8/WebApi/data/v3/2021",
    "xsdMetadata": "https://win-qv87ia1brr8/WebApi/metadata/2021/xsd"
  }
}
```

2021-07-01 16:18 UTC, jamessmckay requested changes
@raghuramakrishna 
Getting an error with the configuration of the admin app.

```
2021-07-01 09:11:43,033 [6] ERROR DbUp [(null)] - Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EdFi_Ods" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\AdminApp'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:35cf9387-41f2-4a7d-bb5e-e597829b53f3
Error Number:4060,State:1,Class:11
2021-07-01 09:11:43,052 [6] ERROR EdFi.Ods.AdminApp.Web.Controllers.SetupController [(null)] - Setup failed
System.Exception: Error while creating report views.
 ---> System.Data.SqlClient.SqlException (0x80131904): Cannot open database "EdFi_Ods" requested by the login. The login failed.
Login failed for user 'IIS APPPOOL\AdminApp'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:35cf9387-41f2-4a7d-bb5e-e597829b53f3
Error Number:4060,State:1,Class:11
   --- End of inner exception stack trace ---
   at EdFi.Ods.AdminApp.Management.Database.Ods.Reports.ReportViewsSetUp.CreateReportViews(String odsInstanceName, ApiMode apiMode) in D:\BuildAgent\work\d680145f3c8e7bb3\Application\EdFi.Ods.AdminApp.Management\Database\Ods\Reports\ReportViewsSetUp.cs:line 33
   at EdFi.Ods.AdminApp.Management.OdsInstanceServices.OdsInstanceFirstTimeSetupService.CompleteSetup(OdsInstanceRegistration odsInstanceRegistration, CloudOdsClaimSet claimSet, ApiMode apiMode) in D:\BuildAgent\work\d680145f3c8e7bb3\Application\EdFi.Ods.AdminApp.Management\OdsInstanceServices\OdsInstanceFirstTimeSetupService.cs:line 48
   at EdFi.Ods.AdminApp.Management.OnPrem.CompleteOnPremFirstTimeSetupCommand.Execute(String odsInstanceName, CloudOdsClaimSet claimSet, ApiMode apiMode) in D:\BuildAgent\work\d680145f3c8e7bb3\Application\EdFi.Ods.AdminApp.Management.OnPrem\CompleteOnPremFirstTimeSetupCommand.cs:line 58
   at EdFi.Ods.AdminApp.Web.Controllers.SetupController.<CompleteFirstTimeSetup>b__8_0() in D:\BuildAgent\work\d680145f3c8e7bb3\Application\EdFi.Ods.AdminApp.Web\Controllers\SetupController.cs:line 64
   at EdFi.Ods.AdminApp.Web.Controllers.SetupController.RunSetup(Func`1 setupAction) in D:\BuildAgent\work\d680145f3c8e7bb3\Application\EdFi.Ods.AdminApp.Web\Controllers\SetupController.cs:line 89
```

2021-07-02 17:01 UTC, vimayya approved these changes

2021-07-02 17:02 UTC, merged